# Generated by Django 4.1 on 2022-08-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire_reunion_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=45, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_reunion', models.CharField(max_length=30)),
                ('date_envoi', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
