# Generated by Django 4.1 on 2022-08-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire_postuler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire_postuler',
            name='date_envoie',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
