# Generated by Django 4.1 on 2022-08-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaire_postuler', '0002_formulaire_postuler_date_envoie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaire_postuler',
            name='telephone',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
